vocab_test/vocab_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include("word.urls")),
]

vocab_test/word/urls.py
from django.urls import path
from . import views

app_name = 'word'

urlpatterns = [
    path("index/", views.index, name="index"),
    path("index/choice/", views.choice, name="choice"),
    path("index/choiceans/<int:question_id>/", views.choiceans, name="choiceans"),
    path("index/write/", views.write, name="write"),
    path("index/writeans/<int:question_id>/", views.writeans, name="writeans"),
    path("<int:wordlist_id>", views.detail, name="detail"),
    path("list/", views.lists, name="list"),
]

vocab_test/word/models.py
from django.db import models

class WordlistE(models.Model):
    num = models.IntegerField(default=0)
    vocab = models.CharField("英単語", max_length=200)
    mean = models.CharField("意味", max_length=200)
    phrase = models.CharField("MINIMAL PHRASES", max_length=300, default=" ")
    yaku = models.CharField("日本語訳", max_length=200, default=" ")
    CHOICES = (
        ("動詞","動詞"),
        ("名詞","名詞"),
        ("形容詞","形容詞"),
        ("副詞","副詞"),
        ("その他","その他"),
        ("熟語","熟語")
    )
    cata = models.CharField("品詞", max_length=100, choices=CHOICES)
    CHOICE = (
        ("赤","赤"),
        ("黄","黄"),
        ("青","青")
    )
    color = models.CharField("色", max_length=20, default="赤", choices=CHOICE)

# verb,nouns,adjective,adverb,others,phrase

vocab_test/word/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import WordlistE
import random

def index(request):
    return render(request, "word/index.html")

def lists(request):
    wordliste = WordlistE.objects.all()
    context = {
        "wordliste": wordliste,
    }
    return render(request, "word/lists.html", context)

def choice(request):
    choice_list =[]
    cata_list =[]
    sentaku_list =[]
    count = WordlistE.objects.count()
    qnum = random.randint(1,count+1)
    question = get_object_or_404(WordlistE, pk=qnum)
    choice_list.append(question)
    for i in range(count):
        word = WordlistE.objects.get(pk=i+1)
        if question.vocab == word.vocab:
            continue
        elif question.cata == word.cata:
            cata_list.append(word)
    qnum = cata_list
    for i in range(3):
        sen = random.choice(cata_list)
        cata_list.remove(sen)
        choice_list.append(sen)
    for i in range(4):
        sentaku = random.choice(choice_list)
        sentaku_list.append(sentaku)
        choice_list.remove(sentaku)
    context = {
        "question":question,
        "sentaku_list":sentaku_list
    }
    return render(request, "word/choice.html", context)

def choiceans(request, question_id):
    question = get_object_or_404(WordlistE, pk=question_id)
    count = WordlistE.objects.count()
    try:
        if request.method == 'POST':
            ans = request.POST.get('cho', '')
            for i in range(count):
                word = WordlistE.objects.get(pk=i+1)
                if ans == question.mean:
                    choice_id = question_id
                    break
                elif ans == word.mean:
                    choice_id = i + 1
                    text = WordlistE.objects.get(pk=choice_id)
                    break
                elif i == 4:
                    choice_id = 0
            if choice_id == 0:
                typ = "3"
                context ={
                    "question": question,
                    "typ":typ,
                }
            elif question_id == choice_id: 
                typ = "1"
                context ={
                    "question": question,
                    "typ":typ,
                }
            elif choice_id != 0:
                typ = "2"
                context ={
                    "question": question,
                    "text": text,
                    "typ":typ,
                }
            return render(request, "word/choiceans.html", context)
        else:
            return HttpResponse("エラーが発生しました")
    except (WordlistE.DoesNotExist):
        return render(request, "word/choiceans.html")

def write(request):
    wordliste = WordlistE.objects.all()
    question = random.choice(wordliste)
    context = {
        "question": question,
        "wordliste": wordliste,
    }
    return render(request, "word/write.html", context)

def writeans(request, question_id):
    count = WordlistE.objects.count()
    question = get_object_or_404(WordlistE, pk=question_id)
    try:
        if request.method == 'POST':
            ans = request.POST.get('text', '')
            text_id = 0
            for i in range(count):
                word = WordlistE.objects.get(pk=i+1)
                if word.vocab == ans:
                    text_id = i + 1
                    text = WordlistE.objects.get(pk=text_id)
                    break
            if text_id == 0:
                typ = "3"
                context ={
                    "question": question,
                    "typ":typ,
                }
            if question_id == text_id: 
                typ = "1"
                context ={
                    "question": question,
                    "typ":typ,
                }
            elif text_id != 0:
                typ = "2"
                context ={
                    "question": question,
                    "text": text,
                    "typ":typ,
                }
            return render(request, "word/writeans.html", context)
        else:
            return HttpResponse("エラーが発生しました")
    except (WordlistE.DoesNotExist):
        return render(request, "word/writeans.html")


def detail(request, wordlist_id):
    wordliste = get_object_or_404(WordlistE, pk=wordlist_id)
    context = {
        "wordliste": wordliste,
    }
    return render(request, "word/detail.html", context)

vocab_test/word/templates/word/choice.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>選択問題</title>
    <link rel="stylesheet" type="text/css" href="{% static 'word/css/choice.css' %}"/>
</head>
<body>
    <h1>選択問題</h1>
    <h2>{{ question.vocab }}</h2>
    <form  action="{% url 'word:choiceans' question.id %}" method="POST">
        {% csrf_token %}
        {% for sen in sentaku_list %}
            <label><input type="radio", name="cho", value={{sen.mean}}>{{ sen.mean }}</label>
            <br>
        {% endfor %}
        <input type="submit" name="submit" value="送信">
    </form>
</body>
</html>

vocab_test/word/templates/word/choiceans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="choiceans">
    <title>choiceanswer</title>
</head>
<body>
    <h3>答え: {{ question.mean }}</h3>
    <p>{{ question.vocab }}</p>
    <form action="{% url 'word:detail' question.id %}" method="POST">
        {% csrf_token %}
        <input type="submit" name="check" value="詳細ページへ">
    </form>
    {% if typ == "1" %}
        <h4>正解</h4>
    {% elif typ == "2" %}
        <h4>不正解</h4>
        <h3>あなたの回答</h3>
        <p>{{ text.vocab }}</p>
        <p>{{ text.mean }}</p>
        <form action="{% url 'word:detail' text.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" name="check" value="詳細ページへ">
        </form>
    {% elif typ == "3" %}
        <p>正常に選択されていません</p>
    {% endif %}
    <br><br>
    <form action="{% url 'word:choice' %}" method="POST">
        {% csrf_token %}
        <input type="submit" name="submit" value="戻る">
</body>
</html>

vocab_test/word/templates/word/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>詳細ページ</title>
    <link rel="stylesheet" type="text/css" href="{% static 'word/css/detail.css' %}"/>
</head>
<body>
    <h1>{{ wordliste.num }}. {{ wordliste.vocab }}</h1>
    <br>
    <h3>{{ wordliste.cata }}</h3>
    <p>{{ wordliste.mean }}</p>
    <p>{{ wordliste.phrase }}</p>
    <p>{{ wordliste.yaku }}</p>
    {% if wordliste.color == "赤" %}
        <p class="red">{{ wordliste.color }}</p>
    {% elif wordliste.color == "緑" %}
        <p class="green">{{ wordliste.color }}</p>
    {% elif wordliste.color == "青" %}
        <p class="blue">{{ wordliste.color }}</p>
    {% else %}
        <p>{{ wordliste.color }}</p>
    {% endif %}
    <br><br>
    <form action="{% url 'word:choice' %}" method="POST">
        {% csrf_token %}
        <input type="submit" name="submit" value="選択問題へ">
    </form>
    <br>
    <form action="{% url 'word:write' %}" method="POST">
        {% csrf_token %}
        <input type="submit" name="submit" value="書き問題へ">
    </form>
</body>
</html>

vocab_test/word/templates/word/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>単語テスト</title>
    <link rel="stylesheet" type="word/css" href="{% static 'word/css/index.css' %}"/>
</head>
<body>
    <p>単語テスト</p>
    <a href="choice/">選択問題</a>
    <a href="write/">書き問題</a>

</body>
</html>

vocab_test/word/templates/word/lists.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>一覧ページ</title>
        <link rel="stylesheet" type="text/css" href="{% static 'word/css/lists.css' %}"/>
    </head>
    <body>
        {% for word in wordliste %}
            <ul>
                <li>{{ word.num }}. <a href="{% url 'word:detail' word.id %}">{{ word.vocab }}</a></li>
            </ul>
            <br>
        {% endfor %}
    </body>
</html>

vocab_test/word/templates/word/write.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>書き問題</title>
    </head>
    <body>
        <h2>wordtest</h2>
        <form action="{% url 'word:writeans' question.id %}" method="POST">
            {% csrf_token %}
            <label>記入:<input type="text" name="text"></label>
            <input type="submit" name="submit" value="送信">
            <p>{{ question.mean }}</p>
        </form>    
    </body>
</html>

vocab_test/word/templates/word/writeans.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>書き正解</title>
    </head>
    <body>
        <h3>答え: {{ question.vocab }}</h3>
        <p>{{ question.mean }}</p>
        <form action="{% url 'word:detail' question.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" name="check" value="詳細ページへ">
        </form>
        {% if typ == "1" %}
            <h4>正解</h4>
        {% elif typ == "2" %}
            <h4>不正解</h4>
            <h3>あなたの回答</h3>
            <p>{{ text.vocab }}</p>
            <p>{{ text.mean }}</p>
            <form action="{% url 'word:detail' text.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" name="check" value="詳細ページへ">
            </form>
        {% elif typ == "3" %}
            <p>このデータベース上にあなたの回答はありません</p>
        
        {% endif %}
        <br><br>
        <form action="{% url 'word:write' %}" method="POST">
            {% csrf_token %}
            <input type="submit" name="submit" value="戻る">
        </form>
    </body>
</html>